### ISSUE TITLE
Team info pop up

### ISSUE THREAD

**Issue by JessWakelin** [shescoding/shescoding-dot-org#49]
I was wondering if you thought about the photos or name being pressed and the information appearing rather than scrolling and it appearing?

**Comment by natsteinmetz** [comment]
Yeah, we need to overthink the team page on mobile, as it is hard to make the current design work well on mobile.

**Comment by cherchezlafemme** [comment]
https://github.com/shescoding/shescoding-dot-org/projects/1#card-14110392

**Comment by natsteinmetz** [comment]
As of right now the pop up doesn't appear anymore on scroll. We'll need to think about what we want to happen on mobile, or rather: do we want the hover info to be visible?

**Comment by booellean** [comment]
I will take this on

**Comment by natsteinmetz** [comment]
Thanks, @booellean :)

**Comment by booellean** [comment]
Hey everyone, I wanted to give you an update. Hopefully this will help people in the future.

I've been having a heck of time with postgres and creating a database for the app. After some hours of debugging, I found I am not able to create a database because the dualboot I am using to run Ubuntu from a chromebook is preventing postgres commands from executing.

In short, postgres has very limited operations in ubuntu, if ubuntu is dual booted from a chromebook.

Knowing this, I'm moving the project to my home computer which runs windows. Sorry for that delay :(

**Comment by booellean** [comment]
Hey everyone, I have a request.

I've added the necessary changes to make team info static on the page and not "pop up" with a touch event scroll. However, I could only test this in my files because, despite my best efforts, I am unable to run a development application. It appears that ubuntu and ubuntu on windows have some error with the pg gem that's causing issues and I was unable to find a fix.

Anyways, if anyone wants to review the changes I've made and test them on a mac machine with a touch screen, you can see how the function operates. It's a little clunky, so maybe adding bootstrap stylings like an accordian?

https://github.com/booellean/shescoding-dot-org

changes are in vendor/assets/javascripts/mobile.js <-- new file
                        app/assets/stylesheets/team.css.scss

**Comment by cherchezlafemme** [comment]
@booellean what is the branch name? I don't see any recent branches in your forked repo.

**Comment by cherchezlafemme** [comment]
@booellean can you add a link here to what's the branch you have the suggested changes?

**Comment by booellean** [comment]
Hello @cherchezlafemme and @natsteinmetz

I was able to get a Windows development environment running and I tested this branch. It 100% works and will allow users to read the user tooltip (since it no longer appears on hover) info, but only if they use their touch screens (visible positioning in the DOM)

https://github.com/booellean/shescoding-dot-org/tree/mobile-touch-data

Question for the both of you, would you like me to edit the README.md to include how to set up a Windows 10 development environment? It's super complicated and took me 4 hours to finally achieve; I'd really like to save other users time/expand our user base for development.

Please let me know, and instruct in how I would do so.

**Comment by cherchezlafemme** [comment]
@booellean yes, please open a PR with suggested updates to readme (from a different separate branch will be best, so that we can merge things independently). Better readme would be amazing.
I will look over PR as soon as I have some time :) thank you for your contributions!

**Comment by cherchezlafemme** [comment]
addressed by https://github.com/shescoding/shescoding-dot-org/pull/173
merged to master 01/16/19

**Comment by natsteinmetz** [comment]
@booellean I can't agree more - thanks for offering to edit the Readme to include setting up a Windows 10 environment. I think that will be of great help to a lot of people!

**Comment by booellean** [comment]
Thank you @natsteinmetz ^_^
