### ISSUE TITLE
Resources list to be displayed as a drop down list

### ISSUE THREAD

**Issue by JessWakelin** [shescoding/shescoding-dot-org#53]
Better UI would be to change list to a dropdown menu

![dropdown copy](https://cloud.githubusercontent.com/assets/11992232/7201524/159b8ba2-e500-11e4-938f-46f04887c57b.png)

**Comment by Videhi** [comment]
Samsung S4 - Resources multi-selection

This tagging/word cloud sort of interface is fine, but may not give flexibility to select multiple categories at once. Also, a sort of drop-down list might help reduce the noise..its kinda traffic heavy to eyes…

![screenshot_2015-04-17-13-15-46](https://cloud.githubusercontent.com/assets/11992207/7202234/4b77e57e-e508-11e4-98d9-e22f5b24d6ea.jpg)

**Comment by natsteinmetz** [comment]
Once screenspace gets reduced, the left sidebar with categories disappears, and the categories appear on top. Instead, create a hamburger dropdown for the categories in that case.

**Comment by Elenaires** [comment]
I will look into this :)

**Comment by Elenaires** [comment]
This is what I have got so far:

When screen size is reduced
![image](https://user-images.githubusercontent.com/16939909/47531065-5a1bd180-d861-11e8-947d-95202790ebda.png)

When dropdown button is clicked
![image](https://user-images.githubusercontent.com/16939909/47531130-87687f80-d861-11e8-83c8-494ceba1e912.png)

Does it look all right?

I also ran tests with RSpec Rails:
![image](https://user-images.githubusercontent.com/16939909/47531263-f04ff780-d861-11e8-98ca-e66d1005c999.png)

I am not too sure what the outcome means. Is it all good since it has 0 failure?

**Comment by natsteinmetz** [comment]
Hi @Elenaires - I have not yet had a chance to try it out. But from the visual point of view, could you align the dropdown button on the left instead of having it centered? 

Regarding the ests, you did not add any tests, and didn't touch anything that was tested, so yeah, this looks allright. :)

**Comment by Elenaires** [comment]
Sure @natsteinmetz , will do that.

**Comment by Elenaires** [comment]
I have aligned the dropdown button to the left and submitted my pull request. This is my first time contributing to open source so please let me know if there is anything that I could do better. Thanks. ;)

**Comment by cherchezlafemme** [comment]
Merged to master 10/28/2018. PR: https://github.com/shescoding/shescoding-dot-org/pull/138
