### ISSUE TITLE
Samsung S4 - Team details mismatch

### ISSUE THREAD

**Issue by Videhi** [shescoding/shescoding-dot-org#57]
http://shescoding-wamuq6fved.elasticbeanstalk.com/team 

Please see more details in the screenshot. 

![screenshot_2015-04-17-13-16-42](https://cloud.githubusercontent.com/assets/11992207/7202031/32432b10-e506-11e4-8c0a-48b60365d4e5.png)

**Comment by natsteinmetz** [comment]
Fixed by #61 #62 and #64 . Tapping now links to the LinkedIn page of the person. When getting back to this tab, the tooltip is shown at the right place.

A better solution might be to on tap show the tooltip, and let the user tap on the name to get the LinkedIn profile. We can change that in the future.
